name: logspectra
services:
  app:
    image: registry.anri.my.id/me/logspectra:latest
    container_name: logspectra
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
    depends_on:
      - database

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
