-- AlterTable
ALTER TABLE "anomaly_logs" ADD COLUMN     "avg_response_size" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "avg_url_length" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "behavior_risk_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "error_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "has_ioc" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "has_susp_ua" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "model_risk_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "response_size_std" DOUBLE PRECISION NOT NULL DEFAULT 0;
